networks:

  itmo:

services:

  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: naku
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      - itmo

  wildfly:
    build:
      context: ./
    networks:
      - itmo
    ports:
      - "9385:8080"
    depends_on:
      - database